# Generated by Django 6.0.7 on 2026-07-23 18:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('whatsapp', models.CharField(help_text='Somente dígitos com DDD, ex: 48999999999', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('arrais', 'Arrais-Amador'), ('motonauta', 'Motonauta'), ('mestre', 'Mestre-Amador'), ('capitao', 'Capitão-Amador')], max_length=20, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, default=Decimal('29.90'), max_digits=8)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Aguardando pagamento'), ('pago', 'Pago'), ('confirmado', 'Confirmado na turma'), ('credito', 'Convertido em crédito'), ('cancelado', 'Cancelado'), ('estornado', 'Estornado')], default='pendente', max_length=20)),
                ('usou_credito', models.BooleanField(default=False)),
                ('token_acesso', models.CharField(editable=False, max_length=64, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='cliente.cliente')),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_gerados', to='cliente.inscricao')),
                ('usado_em', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_usados', to='cliente.inscricao')),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('data_hora', models.DateTimeField()),
                ('stream_url', models.URLField(blank=True, help_text='Link da transmissão OBS (YouTube Live, Vimeo, player próprio, etc.)')),
                ('status', models.CharField(choices=[('aberta', 'Aberta para inscrição'), ('confirmada', 'Turma confirmada (≥ mínimo)'), ('credito', 'Não atingiu mínimo — créditos emitidos'), ('encerrada', 'Encerrada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('min_alunos', models.PositiveSmallIntegerField(default=10, help_text='Mínimo de pagamentos confirmados para fechar a turma')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lives', to='cliente.curso')),
            ],
            options={
                'verbose_name': 'Live',
                'verbose_name_plural': 'Lives',
                'ordering': ['data_hora'],
            },
        ),
        migrations.AddField(
            model_name='inscricao',
            name='live',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='cliente.live'),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('estornado', 'Estornado'), ('expirado', 'Expirado'), ('falha', 'Falha')], default='pendente', max_length=20)),
                ('asaas_payment_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('asaas_customer_id', models.CharField(blank=True, max_length=64)),
                ('pix_qr_code', models.TextField(blank=True, help_text='Imagem QR em base64 ou URL')),
                ('pix_copia_cola', models.TextField(blank=True)),
                ('invoice_url', models.URLField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='cliente.inscricao')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together={('cliente', 'live')},
        ),
    ]
