# Generated by Django 6.0.7 on 2026-07-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='asaas_payment_id',
            new_name='livepix_payment_id',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='asaas_customer_id',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='livepix_reference',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='invoice_url',
            field=models.URLField(blank=True, help_text='URL do checkout LivePix'),
        ),
    ]
