# Generated by Django 6.0.7 on 2026-07-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_livepix_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='min_alunos_padrao',
            field=models.PositiveSmallIntegerField(default=5, help_text='Mínimo de alunos pagos para fechar turma neste curso'),
        ),
    ]
