# Generated by Django 6.0.7 on 2026-07-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_livepixcampanha_widget_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='min_alunos_padrao',
            field=models.PositiveSmallIntegerField(default=5, help_text='Mínimo de alunos pagos para fechar turma neste curso (padrão das lives)'),
        ),
    ]
