# Generated by Django 6.0.7 on 2026-07-25 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_alter_curso_min_alunos_padrao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='live',
            options={'ordering': ['data_hora'], 'verbose_name': 'Curso agendado', 'verbose_name_plural': 'Cursos agendados'},
        ),
        migrations.AlterField(
            model_name='curso',
            name='min_alunos_padrao',
            field=models.PositiveSmallIntegerField(default=5, help_text='Mínimo de alunos pagos para fechar turma neste curso (padrão das turmas)'),
        ),
        migrations.AlterField(
            model_name='gravacao',
            name='live',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gravacoes', to='cliente.live', verbose_name='Curso agendado'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='live',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='cliente.live', verbose_name='Curso agendado'),
        ),
        migrations.AlterField(
            model_name='livepixcampanha',
            name='live',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livepix_campanha', to='cliente.live', verbose_name='Curso agendado'),
        ),
        migrations.AlterField(
            model_name='material',
            name='live',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='cliente.live', verbose_name='Curso agendado'),
        ),
    ]
