# Generated by Django 6.0.7 on 2026-07-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_rename_live_labels_to_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('arrais', 'Arrais-Amador'), ('motonauta', 'Motonauta'), ('arrais_motonauta', 'Arrais-Amador e Motonauta'), ('mestre', 'Mestre-Amador'), ('capitao', 'Capitão-Amador'), ('operador_radio', 'Operador Radiotelefonista Geral')], max_length=20),
        ),
    ]
