# Generated by Django 6.0.7 on 2026-07-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_curso_operador_radio'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='mostrar_aproveite',
            field=models.BooleanField(default=False, help_text='Exibe o selo “Aproveite!” ao lado do preço na página de cursos.', verbose_name='Banner Aproveite!'),
        ),
    ]
